name: release

on:
  push:
    tags:
      - v*

jobs:
  releaser:
    runs-on: ubuntu-22.04
    steps:
      - name: Clean up
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /usr/local/.ghcup
          sudo docker system prune -af
          sudo df -h

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "oldstable"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: setup release environment
        run: |-
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}' > .release-env

      - name: goreleaser release
        run: make release
